### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by MentalGear** [shamscorner/sveltekit-stackter#2]
Thanks for the template, but on a clean install, it's not building: Error: build folder is missing.

**Comment by shamscorner** [comment]
I am really sorry for getting back to you this late. Actually, I didn't think anyone would notice this template 😄. I was so nonchalant about it that I kinda forgot about this template.

I have updated everything to the latest version & removed some unnecessary things from this template. I hope you would be able to build this time even though I think this isn't relevant to you anymore 😄.

Thanks for the feedback 😊
